exp_params:
#  dataset: 'isolet_subset'
  dataset: 'HAR_2'
  latent_dim: 2
  stream_rate: 1
  initial_data_num: 300
  window_size: 50000
  vis_iter: 1000
  save_iter: 100000
  eval_iter: 1
  make_animation: False

method_params:
  n_neighbors: 30