exp_params:
#  dataset: 'isolet_subset'
  dataset: 'food'
  input_dims: 512   # x for vectors or (h, w, c) for images
  latent_dim: 2
  stream_rate: 2
  indices_file_path: -1
  initial_data_num: 300
  vis_iter: 50


method_params:
  method: "CDR"
  initial_train_epoch: 100
  finetune_epoch: 50
  shift_buffer_size: 30
  batch_size: 256
  LR: 0.001
  n_neighbors: 10
  optimizer: "adam" # adam or sgd
  scheduler: "multi_step" # cosine or multi_step or on_plateau
  temperature: 0.15
  split_upper: 0.1
  split_lower: 0.005
  alpha: 6
  separation_begin_ratio: 0.25
  steady_begin_ratio: 0.9
  ckpt_path: None


debug_params:
  epoch_print_inter: 0.1
  vis_inter: 0.5
  model_save_inter: 1.0
  eval_inter: 1.0 # 0 indicates that no test during training process