exp_params:
#  dataset: 'isolet_subset'
  dataset: 'electric_devices'
  input_dims: 96   # x for vectors or (h, w, c) for images
  latent_dim: 2
  stream_rate: 1
  initial_data_num: 300
  window_size: 5000
  vis_iter: 1000
  save_iter: 100000
  eval_iter: 30000
  make_animation: False


method_params:
  initial_train_epoch: 200
  finetune_epoch: 50
  batch_size: 512
  LR: 0.001
  n_neighbors: 15
  temperature: 0.15
  split_upper: 0.11
  split_lower: 0.005
  alpha: 6
  separation_begin_ratio: 0.20
  steady_begin_ratio: 0.9