exp_params:
#  dataset: 'isolet_subset'
  dataset: 'food'
  input_dims: 617   # x for vectors or (h, w, c) for images
  latent_dim: 2
  stream_rate: 100
  indices_file_path: -1
  initial_data_num: 300
  vis_iter: 50

method_params:
  forgetting_factor: 1.0