exp_params:
#  dataset: 'isolet_subset'
  dataset: 'food'
  input_dims: 512   # x for vectors or (h, w, c) for images
  latent_dim: 2
  stream_rate: 1
  initial_data_num: 300
  window_size: 2000
  vis_iter: 100
  save_iter: 500000
  eval_iter: 200
  make_animation: False

method_params:
  n_neighbors: 10