exp_params:
#  dataset: 'isolet_subset'
  dataset: 'chess'
  latent_dim: 2
  stream_rate: 1
  initial_data_num: 300
  window_size: 2000
  vis_iter: 1000
  save_iter: 500000
  eval_iter: 10000
  make_animation: False

method_params:
  n_neighbors: 15