exp_params:
#  dataset: 'isolet_subset'
  dataset: 'arem'
  latent_dim: 2
  stream_rate: 1
  initial_data_num: 300
  window_size: 5000
  vis_iter: 100
  save_iter: 50000
  eval_iter: 30000
  make_animation: False

method_params:
  forgetting_factor: 1.0