exp_params:
#  dataset: 'isolet_subset'
  dataset: 'activity_rec'
  latent_dim: 2
  stream_rate: 1
  initial_data_num: 300
  window_size: 3000
  vis_iter: 1000
  save_iter: 500000
  eval_iter: 10000
  make_animation: False

method_params:
  buffer_size: 200
  eta: 0.99