exp_params:
#  dataset: 'isolet_subset'
  dataset: 'food'
  input_dims: 512   # x for vectors or (h, w, c) for images
  latent_dim: 2
  stream_rate: 1
  indices_file_path: -1
  initial_data_num: 300
  vis_iter: 100
  save_iter: 500000
  eval_iter: 100
  make_animation: True

method_params:
  buffer_size: 200
  eta: 0.99